version: '3'
services:
  protonvpn:
    image: docker.io/emackie/protonvpn:latest
    container_name: protonvpn
    environment:
      PROTONVPN_USERNAME: ${SEEDBOX_PROTONVPN_USERNAME}
      PROTONVPN_PASSWORD: ${SEEDBOX_PROTONVPN_PASSWORD}
      PROTONVPN_TIER: ${SEEDBOX_PROTONVPN_TIER:-2}
      PROTONVPN_SERVER: ${SEEDBOX_PROTONVPN_SERVER:-P2P}
      PROTONVPN_EXCLUDE_CIDRS: ${SEEDBOX_PROTONVPN_EXCLUDE_CIDRS}
      PROTONVPN_MY_IP: ${SEEDBOX_PROTONVPN_MY_IP}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8112:8112
      - 9117:9117
    restart: on-failure

  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: service:protonvpn
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - deluge:/config
      - downloads:/downloads
    depends_on:
      - protonvpn
    restart: on-failure

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    network_mode: service:protonvpn
    environment:
      - TZ=${TZ:-America/Toronto}
      - AUTO_UPDATE=true
    volumes:
      - jackett:/config
      - downloads:/downloads
    depends_on:
      - protonvpn
    restart: on-failure

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    network_mode: service:protonvpn
    depends_on:
      - protonvpn
    restart: on-failure
  
  tdps-downloader:
    image: emackie/tdps-downloader
    container_name: tdps-downloader
    network_mode: service:protonvpn
    environment:
      - TDPS_LOGIN=${SEEDBOX_TDPS_LOGIN}
      - TDPS_PASS=${SEEDBOX_TDPS_PASS}
      - TDPS_PATH=${SEEDBOX_TDPS_PATH}
      - TZ=${TZ:-America/Toronto}
    volumes:
      - content:/app/downloads
    depends_on:
      - protonvpn
    restart: on-failure

volumes:
  content:
    name: seedbox_content
    driver_opts:
      type: "nfs"
      o: "addr=${SEEDBOX_NFS_CONTENT_HOST},rw,nfsvers=4"
      device: "${SEEDBOX_NFS_CONTENT_PATH}"
  deluge:
    name: seedbox_deluge
  downloads:
    name: seedbox_downloads
    driver_opts:
      type: "nfs"
      o: "addr=${SEEDBOX_NFS_DOWNLOADS_HOST},rw,nfsvers=4"
      device: "${SEEDBOX_NFS_DOWNLOADS_PATH}"
  jackett:
    name: seedbox_jackett