version: "3"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - TZ=${TZ:-America/Toronto}
    ports:
      - 32400:32400
    volumes:
      - config:/config
      - content:${PLEXSTACK_CONTENT_DIR:-/content}
      - transcoder:/transcode
    restart: on-failure:5

  backups:
    image: emackie/aws-cli-cron
    container_name: plex-content-backup
    environment:
      - TZ=${TZ:-America/Toronto}
    volumes:
      - aws_credentials:/root/.aws
      - cronjobs:/cron
      - content:/content
    restart: on-failure:5

volumes:
  aws_credentials:
    name: aws_credentials
    driver: local
  cronjobs:
    name: plexstack_cron
    driver: local
  config:
    name: plexstack_config
    driver: local
  content:
    name: plexstack_content
    driver_opts:
      type: "nfs"
      o: "addr=${PLEXSTACK_NFS_CONTENT_HOST},rw,nfsvers=4"
      device: "${PLEXSTACK_NFS_CONTENT_PATH}"
  transcoder:
    name: plexstack_transcoder
    driver: local
